Config = {}

Config.SyncAnimations = {
	{
		name = 'synced',
		label = 'Synkade animationer',
		items = {
		{label = 'Gangsterhälsa på närmsta spelare', data = {lib = 'mp_ped_interaction', anim1 = 'hugs_guy_b', anim2 = 'hugs_guy_a', distans = 1.15, distans2 = 0.0, height = 0.0, spin = 180.0}},
		{label = 'Krama närmsta spelare', data = {lib = 'mp_ped_interaction', anim1 = 'kisses_guy_b', anim2 = 'kisses_guy_b', distans = 1.10, distans2 = -0.1, height = 0.0, spin = 180.0}},
		{label = 'Kyss närmsta spelare', data = {lib = 'mp_ped_interaction', anim1 = 'kisses_guy_a', anim2 = 'kisses_guy_a', distans = 1.15, distans2 = 0.0, height = 0.0, spin = 180.0}},
		{label = 'Skaka hand med närmsta spelare', data = {lib = 'mp_common', anim1 = 'givetake1_a', anim2 = 'givetake1_a', distans = 0.8, distans2 = 0.05, height = 0.0, spin = 180.0}},
        {label = 'Gör highfive med närmsta spelare', data = {lib = 'mp_ped_interaction', anim1 = 'highfive_guy_a', anim2 = 'highfive_guy_b', distans = 1.2, distans2 = -0.3, height = 0.0, spin = 180.0}},
        {label = 'Gå ner på HAN 1 🔞', data = {lib = 'misscarsteal2pimpsex', anim1 = 'pimpsex_hooker', anim2 = 'pimpsex_pimp', distans = 0.8, distans2 = 0.0, height = 0.0, repet = 1}},
        {label = 'Gå ner på HAN 2 🔞', data = {lib = 'misscarsteal2pimpsex', anim1 = 'pimpsex_hooker', anim2 = 'pimpsex_punter', distans = 0.8, distans2 = 0.0, height = 0.0, repet = 1}},
        {label = 'Ta HENNE mot väggen 🔞', data = {lib = 'misscarsteal2pimpsex', anim1 = 'shagloop_pimp', anim2 = 'shagloop_hooker', distans = 0.8, distans2 = 0.0, height = 0.0, repet = 1}},
		}
	}
}

Config.Animations = {

    {
        name  = 'help',
        label = 'Nödlägen',
        items = {   
        {label = "Bli arresterad", type = "anim", data = {lib = "random@arrests@busted", anim = "idle_a", repet = 1}},  
        {label = "Beskjuten", type = "anim", data = {lib = "anim@heists@ornate_bank@hostages@cashier_a@", anim = "flinch_loop_underfire", repet = 49}},
        {label = "Ligg ner", type = "anim", data = {lib = "anim@heists@ornate_bank@hostages@ped_a@", anim = "flinch_loop_underfire", repet = 1}},
        {label = "Hyka ner", type = "anim", data = {lib = "anim@heists@ornate_bank@hostages@cashier_a@", anim = "flinch_loop_underfire", repet = 1}},
        {label = "Rädd 1", type = "anim", data = {lib = "amb@code_human_cower_stand@male@react_cowering", anim = "base_back_left", repet = 1}},
        {label = "Rädd 2", type = "anim", data = {lib = "anim@heists@fleeca_bank@hostages@ped_d@", anim = "idle", repet = 1}},
        {label = "Rädd 3", type = "anim", data = {lib = "random@domestic", anim = "f_distressed_loop", repet = 1}},
        {label = "Kryp", type = "anim", data = {lib = "move_injured_ground", anim = "front_loop", repet = 33}},
        {label = "Elshock", type = "anim", data = {lib = "stungun@standing", anim = "damage", repet = 1}},
        {label = "Underlägsen", type = "anim", data = {lib = "amb@code_human_cower_stand@male@react_cowering", anim = "base_right", repet = 1}},
        {label = "Skadat huvudet", type = "anim", data = {lib = "misscarsteal4@actor", anim = "stumble", repet = 33}},

        }
    },

    {
        name  = 'driver',
        label = 'Förarsätet',
        items = {
        {label = "Prata med baksätet", type = "anim", data = {lib = "oddjobs@taxi@driver", anim = "leanover_idle", repet = 32}},
        {label = "Ge/Ta genom rutan", type = "anim", data = {lib = "oddjobs@taxi@cyi", anim = "std_hand_off_ps_passenger", repet = 32}},
        {label = "Upp med händerna", type = "anim", data = {lib = "anim@mp_player_intincarsurrenderstd@ds@", anim = "idle_a", repet = 33}},
        {label = "Träna på gitarren", type = "anim", data = {lib = "anim@mp_player_intincarair_guitarstd@ds@", anim = "idle_a", repet = 33}},
        {label = "Trumma lite", type = "anim", data = {lib = "anim@mp_player_intincarair_synthstd@ds@", anim = "idle_a", repet = 33}},
        {label = "Chicken", type = "anim", data = {lib = "anim@mp_player_intincarchicken_tauntstd@ds@", anim = "idle_a", repet = 49}},
            }
        },

    {
         name  = 'passenger',
         label = 'Passagerarsätet',
         items = {		
         {label = "Uttråkad", type = "anim", data = {lib = "amb@code_human_in_car_idles@low@ps@idle_d", anim = "idle_k", repet = 1}},
         {label = "Spy ur bilen", type = "anim", data = {lib = "oddjobs@taxi@tie", anim = "vomit_outside"}},
             }
         },

    {
		 name  = 'festives',
         label = 'Fest',
         items = {
         {label = "Spela ett instrument", type = "scenario", data = {anim = "WORLD_HUMAN_MUSICIAN"}},
         {label = "Discojockey 1", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@dj", anim = "dj", repet = 1}},
         {label = "Discojockey 2", type = "anim", data = {lib = "anim@amb@nightclub@djs@dixon@", anim = "dixn_dance_a_dixon", repet = 1}},
         {label = "Discojockey 3", type = "anim", data = {lib = "anim@amb@nightclub@djs@tale_of_us@", anim = "tou_dance_a_cc", repet = 1}},
         {label = "Hinka Pilsner", type = "scenario", data = {anim = "WORLD_HUMAN_PARTYING"}},
         {label = "Sten, sax, påse", type = "anim", data = {lib = "amb@code_human_in_car_mp_actions@fist_pump@low@ps@base", anim = "idle_a", repet=1}},
         {label = "Välj Sten", type = "anim", data = {lib = "amb@code_human_in_car_mp_actions@fist_pump@low@ps@base", anim = "enter", repet=2}},
         {label = "Välj Sax", type = "anim", data = {lib = "amb@code_human_in_car_mp_actions@v_sign@low@ps@base", anim = "idle_a", repet=1}},
         {label = "Välj Påse", type = "anim", data = {lib = "anim@mp_player_intupperwave", anim = "idle_a_fp", repet=2}},
         {label = "Luftgitarr", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@air_guitar", anim = "air_guitar"}},
         {label = "Luftjucka", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@air_shagging", anim = "air_shagging"}},
         {label = "Rock'n'roll", type = "anim", data = {lib = "mp_player_int_upperrock", anim = "mp_player_int_rock", repet = 1}},
         {label = "Servera en drink", type = "anim", data = {lib = "anim@amb@nightclub@mini@drinking@bar@drink_v2@base", anim = "intro_bartender", repet = 1}},
         {label = "Häll upp en shot", type = "anim", data = {lib = "mini@drinking", anim = "shots_barman_a", repet = 0}},
         {label = "Vinnare", type = "anim", data = {lib = "mini@dartsoutro", anim = "darts_outro_01_guy1", repet = 0}},
         {label = "Förlorare", type = "anim", data = {lib = "mini@dartsoutro", anim = "darts_outro_01_guy2", repet = 0}},
         {label = "Spela synth", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@air_synth", anim = "air_synth"}},
         {label = "Visa respekt", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@bro_love", anim = "bro_love"}},
         {label = "Vann ett race", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@chin_brush", anim = "chin_brush"}},
         {label = "Delicious", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@finger_kiss", anim = "finger_kiss"}},
         {label = "Jazz händer", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@jazz_hands", anim = "jazz_hands"}},
         {label = "Nu ska vi krossa dem", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@knuckle_crunch", anim = "knuckle_crunch"}},
         {label = "Skulle inte tro det", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@no_way", anim = "no_way"}},
         {label = "Peta i näsan", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@nose_pick", anim = "nose_pick"}},
         {label = "Hälsa till publiken", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@wave", anim = "wave"}},
         {label = "Sitter redo att dra en lina", type = "anim", data = {lib = "anim@amb@nightclub@peds@", anim = "missfbi3_party_snort_coke_b_male3", repet = 1}},

        }
    },

    {          
        name = 'Dances',
        label = 'Danser',
        items = {
        {label = "Dans 1 (Finska)", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_1@monologue_1a", anim = "mtn_dnc_if_you_want_to_get_to_heaven", repet = 1}},
        {label = "Dans 2 (Skakar loss)", type = "anim", data = {lib = "missfam2leadinoutmcs3", anim = "onboat_leadin_tracy", repet = 1}},
        {label = "Dans 3 (Snurrar)", type = "anim", data = {lib = "misschinese2_crystalmazemcs1_ig", anim = "dance_loop_tao", repet = 1}},
        {label = "Dans 4 (Krog)", type = "scenario", data = {anim = "WORLD_HUMAN_STRIP_WATCH_STAND"}},
        {label = "Dans 5 (Rave)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@black_madonna_entourage@", anim = "hi_dance_facedj_09_v2_male^5", repet = 1}},
        {label = "Dans 6 (Bar-bord)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@club_ambientpeds_transitions@", anim = "trans_li-mi_to_mi-hi_09_v1_male^6", repet = 1}},
        {label = "Dans 7 (Krökar)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@club_ambientpeds@med-hi_intensity", anim = "mi-hi_amb_club_09_v1_male^1", repet = 1}},
        {label = "Dans 8 (Dansfestival)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_09_v1_male^1", repet = 1}},
        {label = "Dans 9 (Galen)", type = "anim", data = {lib = "anim@arena@celeb@podium@no_prop@", anim = "dance_a_1st", repet = 1}},
        {label = "Dans 10 (Gäng)", type = "anim", data = {lib = "missfbi3_sniping", anim = "dance_m_default", repet = 1}},
        {label = "Dans 11 (Pinsam)", type = "anim", data = {lib = "move_clown@p_m_zero_idles@", anim = "fidget_short_dance", repet = 1}},
        {label = "Dans 12 (Stripptease 1)", type = "anim", data = {lib = "mp_am_stripper", anim = "lap_dance_girl", repet = 1}},
        {label = "Dans 13 (Stripptease 2)", type = "anim", data = {lib = "oddjobs@assassinate@multi@yachttarget@lapdance", anim = "yacht_ld_f", repet = 1}},
        {label = "Dans 14 (Farsan baloo)", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_2@monologue_2a", anim = "mnt_dnc_angel", repet = 1}},
        {label = "Dans 15 (Snurrande finsk)", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_3@monologue_3a", anim = "mnt_dnc_buttwag", repet = 1}},
        {label = "Dans 16 (Stepande finsk)", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_4@monologue_4a", anim = "mnt_dnc_verse", repet = 1}},
        {label = "Dans 17 (Absolut Freakout)", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@freakout", anim = "freakout", repet = 1}},
        -- dansa till dance 
        {label = "Dans 18 (Dancemusik 1)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups_transitions@", anim = "trans_dance_crowd_mi_to_li_12_v1_male^2", repet = 1}},
        {label = "Dans 19 (Dancemusik 2)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups_transitions@", anim = "trans_dance_crowd_mi_to_li_12_v1_male^3", repet = 1}},
        {label = "Dans 20 (Dancemusik 3)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups_transitions@", anim = "trans_dance_crowd_mi_to_li_12_v1_male^4", repet = 1}},
        {label = "Dans 21 (Dancemusik 4)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups_transitions@", anim = "trans_dance_crowd_mi_to_li_12_v1_male^5", repet = 1}},
        {label = "Dans 22 (Dancemusik 5)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups_transitions@", anim = "trans_dance_crowd_mi_to_li_12_v1_male^6", repet = 1}},
        {label = "Dans 23 (Dancemusik 6)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups_transitions@from_hi_intensity", anim = "trans_dance_crowd_hi_to_li__07_v1_male^1", repet = 1}},
        {label = "Dans 24 (Dancemusik 7)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups_transitions@from_hi_intensity", anim = "trans_dance_crowd_hi_to_li__07_v1_male^2", repet = 1}},
        {label = "Dans 25 (Dancemusik 8)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups_transitions@from_hi_intensity", anim = "trans_dance_crowd_hi_to_li__07_v1_male^3", repet = 1}},
        {label = "Dans 26 (Dancemusik 9)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups_transitions@from_hi_intensity", anim = "trans_dance_crowd_hi_to_li__07_v1_male^4", repet = 1}},
        {label = "Dans 27 (Dancemusik 10)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups_transitions@from_hi_intensity", anim = "trans_dance_crowd_hi_to_li__07_v1_male^6", repet = 1}},
        -- dansa till hardstyle
        {label = "Dans 28 (Hardstyle 1)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_single_props_transitions@", anim = "trans_crowd_prop_hi_to_li_09_v1_male^1", repet = 1}},
        {label = "Dans 29 (Hardstyle 2)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_single_props_transitions@", anim = "trans_crowd_prop_hi_to_li_09_v1_male^2", repet = 1}},
        {label = "Dans 30 (Hardstyle 3)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_single_props_transitions@", anim = "trans_crowd_prop_hi_to_li_09_v1_male^3", repet = 1}},
        {label = "Dans 31 (Hardstyle 4)", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_single_props_transitions@", anim = "trans_crowd_prop_hi_to_li_09_v1_male^6", repet = 1}},
        {label = "Dans 32 (Hardstyle 5)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_06_base_laz", repet = 1}},
        {label = "Dans 33 (Gör vågen)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_li_07_fakedrop_laz", repet = 1}},
        {label = "Dans 34 (Gör roboten)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_15_robot_laz", repet = 1}},
        {label = "Dans 35 (Gör italjenaren)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_17_teapotthrust_laz", repet = 1}},
        {label = "Dans 36 (Sväng loss)", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_trans_07_hi_to_li_laz", repet = 1}},
        {label = "Dans 37 (Opa opa)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_center", repet = 1}},
        {label = "Dans 38 (Piña Colada)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "low_center", repet = 1}},
        {label = "Dans 39 (Chatcha)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "med_center", repet = 1}},
        {label = "Dans 40 (Logic)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "high_center", repet = 1}},
        {label = "Dans 41 (Höga axlar)", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", anim = "high_center", repet = 1}},
        {label = "Dans 42 (i bil: galet mannen)", type = "anim", data = {lib = "misschinese1crazydance", anim = "crazy_dance_1", repet = 1}},
        {label = "Dans 43 (i bil: det svänger)", type = "anim", data = {lib = "misschinese1crazydance", anim = "crazy_dance_2", repet = 1}},
        {label = "Dans 44 (Zombien)", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@cats_cradle", anim = "cats_cradle"}},
        {label = "Dans 45 (Kycklingen)", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@chicken_taunt", anim = "chicken_taunt"}},
        {label = "Dans 46 (Hjärtat)", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@heart_pumping", anim = "heart_pumping"}},
  
  
      }
  }, 

    {
        name  = 'greetings',
        label = 'Hälsningar',
        items = {
        {label = "Tjena!", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_hello"}},
        {label = "Skaka hand", type = "anim", data = {lib = "mp_common", anim = "givetake1_a"}},
	    {label = "Militärhälsing", type = "anim", data = {lib = "mp_player_int_uppersalute", anim = "mp_player_int_salute", repet = 1}},
	    {label = "Boop!", type = "anim", data = {lib = "anim@mp_radio@medium_apment", anim = "action_a_kitchen"}},
	    {label = "Gangsta-dans", type = "anim", data = {lib = "missfbi3_sniping", anim = "dance_m_default"}},
        {label = "Slå händerna samman", type = "anim", data = {lib = "mp_ped_interaction", anim = "handshake_guy_a"}},
        {label = "Skaka hand samt krama", type = "anim", data = {lib = "mp_ped_interaction", anim = "hugs_guy_a"}},
        }
    },

    {
        name  = 'sports',
        label = 'Träning',
        items = {
        {label = "Flexar 1", type = "anim", data = {lib = "amb@world_human_muscle_flex@arms_at_side@base", anim = "base"}},
        {label = "Flexar 2", type = "anim", data = {lib = "amb@world_human_muscle_flex@arms_in_front@base", anim = "base"}},
        {label = "Pumpa stång", type = "scenario", data = {anim = "world_human_muscle_free_weights"}},
        {label = "Armhävningar", type = "anim", data = {lib = "amb@world_human_push_ups@male@base", anim = "base", repet = 1}},
        {label = "Sit-ups", type = "anim", data = {lib = "amb@world_human_sit_ups@male@base", anim = "base", repet = 1}},
        {label = "Fyfan vad slut jag är!", type = "anim", data = {lib = "amb@world_human_jog_standing@male@idle_b", anim = "idle_d"}},
        {label = "Tagga inför hopp", type = "anim", data = {lib = "oddjobs@bailbond_mountain", anim = "base_jump_idle", repet = 1}},
        {label = "Hoppa", type = "anim", data = {lib = "oddjobs@bailbond_mountain", anim = "base_jump_spot", ragdoll = 0}},
        {label = "Tagga", type = "anim", data = {lib = "mini@arm_wrestling", anim = "stand_idle_b"}},
        {label = "Jogga på plats", type = "anim", data = {lib = "amb@world_human_jog_standing@female@base", anim = "base", repet = 1}},
        {label = "Kalle anka fötter", type = "anim", data = {lib = "amb@world_human_drug_dealer_hard@male@base", anim = "base", repet = 1}},
        {label = "Jumping Jacks", type = "anim", data = {lib = "timetable@reunited@ig_2", anim = "jimmy_getknocked", repet = 1}}
        }
    },
    
    {   
        name  = 'work',
        label = 'Jobb',
        items = {
        {label = "Ta noteringar", type = "scenario", data = {anim = "WORLD_HUMAN_CLIPBOARD"}},    
        {label = "Anteckning", type = "scenario", data = {anim = "code_human_medic_time_of_death"}},
        {label = "Polis: Brottsplatsundersökning", type = "anim", data = {lib = "amb@code_human_police_investigate@idle_b", anim = "idle_f"}},
        {label = "Polis: Kikare", type = "scenario", data = {anim = "WORLD_HUMAN_BINOCULARS"}},
        {label = "Polis: Sysslolös", type = "scenario", data = {anim = "world_human_cop_idles"}},
        {label = "Polis: Komradio", type = "anim", data = {lib = "random@arrests", anim = "generic_radio_enter", repet = 10}},
        {label = "Polis: Komradio & Pistol", type = "anim", data = {lib = "random@arrests", anim = "radio_chatter", repet = 3}},
        {label = "Polis: Trafikangivelse", type = "scenario", data = {anim = "WORLD_HUMAN_CAR_PARK_ATTENDANT"}},
        {label = "Polis: Kör åt sidan", type = "anim", data = {lib = "misscarsteal3pullover", anim = "pull_over_right", repet = 0}},
        {label = "Polis: Lyssna på radion", type = "anim", data = {lib = "amb@code_human_police_investigate@idle_a", anim = "idle_b", repet = 1}},
        {label = "Sjukvård: Undersöka", type = "scenario", data = {anim = "CODE_HUMAN_MEDIC_KNEEL"}},
        {label = "Sjukvård: Bröstpump", type = "anim", data = {lib = "mini@cpr@char_a@cpr_str", anim = "cpr_pumpchest", repet = 1}},
        {label = "Sjukvård: Mun mot mun", type = "anim", data = {lib = "mini@cpr@char_a@cpr_str", anim = "cpr_kol", repet = 1}},
        {label = "Sjukvård: Bröstpump misslyckad", type = "anim", data = {lib = "mini@cpr@char_a@cpr_str", anim = "cpr_fail", repet = 1}},
        {label = "Sjukvård: Bröstpump lyckad", type = "anim", data = {lib = "mini@cpr@char_a@cpr_str", anim = "cpr_success", repet = 1}},
        {label = "Patient: Ligg på rygg", type = "anim", data = {lib = "anim@gangops@morgue@table@", anim = "ko_front", repet = 1}},
        --{label = "Mekaniker: Meka under bil", type = "scenario", data = {anim = "world_human_vehicle_mechanic"}}, //Clippar genom väggar
        {label = "Mekaniker: Meka motor", type = "anim", data = {lib = "mini@repair", anim = "fixing_a_ped", repet = 1}},
        {label = "Mekaniker: Skruva däck", type = "anim", data = {lib = "anim@amb@clubhouse@tutorial@bkr_tut_ig3@", anim = "machinic_loop_mechandplayer", repet = 1}},
        {label = "Trädgård: Gräva med liten spade", type = "scenario", data = {anim = "world_human_gardener_plant"}},
        {label = "Trädgård: Lövblåsare", type = "scenario", data = {anim = "WORLD_HUMAN_GARDENER_LEAF_BLOWER"}},
        {label = "Städning: Borsta", type = "scenario", data = {anim = "WORLD_HUMAN_JANITOR"}},
        {label = "Städning: Putsa", type = "scenario", data = {anim = "WORLD_HUMAN_MAID_CLEAN"}},
        {label = "Butiksbiträde: Ge ölback", type = "anim", data = {lib = "mp_am_hold_up", anim = "purchase_beerbox_shopkeeper"}},
	    {label = "Bartender: Hälla upp öl", type = "anim", data = {lib = "mini@drinking", anim = "shots_barman_b"}},
        {label = "Journalist: Tag kort", type = "scenario", data = {anim = "WORLD_HUMAN_PAPARAZZI"}},
        {label = "Clown: Leka staty", type = "scenario", data = {anim = "WORLD_HUMAN_HUMAN_STATUE"}},
        {label = "Uteliggare: Tigg med skylt", type = "scenario", data = {anim = "WORLD_HUMAN_BUM_FREEWAY"}},
        {label = "Uteliggare: Ta en tupplur", type = "scenario", data = {anim = "WORLD_HUMAN_BUM_SLUMPED"}},
        {label = "Uteliggare: Leta i sopor", type = "scenario", data = {anim = "PROP_HUMAN_BUM_BIN"}},
        {label = "Bouncer", type = "anim", data = {lib = "mini@strip_club@idles@bouncer@base", anim = "base", repet = 1}},
        {label = "Proffs i golf", type = "anim", data = {lib = "amb@world_human_golf_player@male@base", anim = "base", repet = 1}},
        {label = "Använd hammare", type = "scenario", data = {anim = "WORLD_HUMAN_HAMMERING"}},
        }
    },

    {
        name  = 'humors',
        label = 'Humor',
        items = {
        {label = "Klappa", type = "scenario", data = {anim = "WORLD_HUMAN_CHEERING"}},
        {label = "Tummenupp!", type = "anim", data = {lib = "mp_action", anim = "thanks_male_06"}},
        {label = "Snyggt där!", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_point"}},
        {label = "Följ med!", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_come_here_soft"}}, 
        {label = "Kom igen då!", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_bring_it_on"}},
        {label = "Pratar du med mig?", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_me"}},
        {label = "Lugna ner dig ", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_easy_now"}},
        {label = "Uppvärmning (slagsmål)", type = "anim", data = {lib = "anim@deathmatch_intros@unarmed", anim = "intro_male_unarmed_e"}},
        {label = "Det är inte möjligt!", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_damn"}},
        {label = "Krama", type = "anim", data = {lib = "mp_ped_interaction", anim = "kisses_guy_a"}},
        {label = "Förbannad", type = "anim", data = {lib = "oddjobs@towingangryidle_a", anim = "idle_b"}},
        {label = "Gråter", type = "anim", data = {lib = "switch@trevor@floyd_crying", anim = "console_wasnt_fun_end_loop_floyd", repet = 49}},
        {label = "Släng kyss♥ 1", type = "anim", data = {lib = "anim@mp_player_intselfieblow_kiss", anim = "exit"}},
        {label = "Släng kyss♥ 2", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@blow_kiss", anim = "blow_kiss"}},
        }
    },

    {
        name  = 'misc',
        label = 'Diverse',
        items = {
        {label = "Sitt på marken 1", type = "anim", data = {lib = "anim@heists@fleeca_bank@ig_7_jetski_owner", anim = "owner_idle", repet = 1}},
        {label = "Sitt på marken 2", type = "anim", data = {lib = "anim@amb@business@bgen@bgen_no_work@", anim = "sit_phone_phoneputdown_idle_nowork", repet = 1}},
        {label = "Sitt på marken 3", type = "anim", data = {lib = "amb@world_human_picnic@male@idle_a", anim = "idle_a", repet = 1}},
        {label = "Sitt på marken 4", type = "anim", data = {lib = "amb@world_human_picnic@female@idle_a", anim = "idle_a", repet = 1}},
        {label = ": Livet är åt helvete", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@lo_alone@", anim = "lowalone_base_laz", repet = 1}},
        {label = ": Nedstämd", type = "anim", data = {lib = "anim@amb@business@bgen@bgen_no_work@", anim = "sit_phone_phoneputdown_sleeping-noworkfemale", repet = 1}},
        {label = ": Rädd 1", type = "anim", data = {lib = "anim@heists@ornate_bank@hostages@hit", anim = "hit_loop_ped_b", repet = 1}},
        {label = ": Rädd 2", type = "anim", data = {lib = "anim@heists@ornate_bank@hostages@ped_c@", anim = "flinch_loop", repet = 1}},
        {label = ": Rädd 3", type = "anim", data = {lib = "anim@heists@ornate_bank@hostages@ped_e@", anim = "flinch_loop", repet = 1}},
        {label = "Sitt mot en vägg 1", type = "scenario", data = {anim = "WORLD_HUMAN_STUPOR"}},
        {label = "Sitt mot en vägg 2", type = "anim", data = {lib = "rcm_barry3", anim = "barry_3_sit_loop", repet = 1}},
        {label = "Sitt mot en vägg 3", type = "anim", data = {lib = "timetable@jimmy@mics3_ig_15@", anim = "idle_a_jimmy", repet = 1}},
        {label = "Sitt mot en vägg 4", type = "anim", data = {lib = "timetable@jimmy@mics3_ig_15@", anim = "mics3_15_base_jimmy", repet = 1}},
        {label = "Sitt mot en vägg 5", type = "anim", data = {lib = "amb@world_human_stupor@male@idle_a", anim = "idle_a", repet = 1}},
        --{label = "Sitt på marken", type = "scenario", data = {anim = "WORLD_HUMAN_PICNIC"}}, -- Clippar genom väggar
        {label = "Sitta och pilla på telefon", type = "anim", data = {lib = "anim@heists@prison_heistunfinished_biztarget_idle", anim = "target_idle", repet = 1}},
        {label = "Sitt på bänk, tänker på livet", type = "anim", data = {lib = "switch@michael@parkbench_smoke_ranger", anim = "parkbench_smoke_ranger_loop", repet = 1}},
        {label = "Sitt på bänk, benen i kors", type = "anim", data = {lib = "missfbi3_party", anim = "snort_coke_a_female", repet = 1}},
        {label = "Sitt på bänk, avslappnad", type = "anim", data = {lib = "switch@michael@on_sofa", anim = "base_michael", repet = 1}},
        {label = ": Med kaffe", type = "scenario", data = {anim = "prop_human_seat_bench_drink"}},
        {label = ": Med öl", type = "scenario", data = {anim = "prop_human_seat_bench_drink_beer"}},
        {label = ": Med Mat", type = "scenario", data = {anim = "prop_human_seat_bench_food"}}, 
        {label = "Sitt på trappsteg och luta dig emot", type = "anim", data = {lib = "timetable@tracy@ig_14@", anim = "ig_14_base_tracy", repet = 1}},
        {label = "Luta dig mot en vägg 1", type = "anim", data = {lib = "amb@world_human_leaning@male@wall@back@legs_crossed@base", anim = "base", repet = 1}},
        {label = "Luta dig mot en vägg 2", type = "anim", data = {lib = "timetable@mime@01_gc", anim = "idle_a", repet = 1}},
        {label = "Luta dig mot en vägg 3", type = "anim", data = {lib = "misscarstealfinale", anim = "packer_idle_1_trevor", repet = 1}},
        {label = "Luta dig mot en vägg 4", type = "anim", data = {lib = "misscarstealfinalecar_5_ig_1", anim = "waitloop_lamar", repet = 1}},
        {label = "Luta dig mot en vägg 5", type = "anim", data = {lib = "rcmjosh2", anim = "josh_2_intp1_base", repet = 1}},
        {label = ": Kolla på naglarna", type = "anim", data = {lib = "friends@fra@ig_1", anim = "base_idle", repet = 1}},
        {label = ": Slumpad", type = "scenario", data = {anim = "WORLD_HUMAN_LEANING"}},
        {label = "Häng över räcke", type = "scenario", data = {anim = "prop_human_bum_shopping_cart"}},
        {label = "Luta dig mot ett räcke", type = "anim", data = {lib = "anim@amb@yacht@rail@standing@male@variant_01@", anim = "base", repet = 1}},
        {label = "Luta dig mot en bardisk", type = "anim", data = {lib = "anim@amb@yacht@rail@standing@male@variant_02@", anim = "base", repet = 1}},
        {label = "Ligga på rygg", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE_BACK"}},
        {label = "Ligga på mage", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE"}},
        {label = "Drick en kopp kaffe", type = "scenario", data = {anim = "WORLD_HUMAN_AA_COFFEE"}},
        {label = "Grilla", type = "scenario", data = {anim = "PROP_HUMAN_BBQ"}},
        {label = "Titanic", type = "anim", data = {lib = "mini@prostitutes@sexlow_veh", anim = "low_car_bj_to_prop_female", repet = 1}},
        {label = "Händerna upp i luften", type = "anim", data = {lib = "anim@mp_rollarcoaster", anim = "hands_up_idle_a_player_one", repet = 49}},
        {label = "Ta en selfie", type = "scenario", data = {anim = "world_human_tourist_mobile"}},
        {label = "Filma med telefonen", type = "scenario", data = {anim = "WORLD_HUMAN_MOBILE_FILM_SHOCKING"}},
        {label = "Tjuvlyssna (Genom vägg)", type = "anim", data = {lib = "mini@safe_cracking", anim = "idle_base", repet = 1}}, 
        {label = "Pilla med mobilen", type = "scenario", data = {anim = "world_human_stand_mobile"}},
        {label = "Vars fan är jag? (karta)", type = "scenario", data = {anim = "world_human_tourist_map"}},
        {label = "Ont i magen(liggandes)", type = "anim", data = {lib = "combat@damage@writheidle_a", anim = "writhe_idle_b", repet = 1}},
        {label = "Kissnödig", type = "anim", data = {lib = "amb@world_human_prostitute@cokehead@base", anim = "base", repet=1}},
        {label = "Nervös", type = "anim", data = {lib = "switch@michael@parkbench_smoke_ranger", anim = "ranger_nervous_loop", repet = 1}},
        {label = "Armarna i kors", type = "anim", data = {lib = "amb@world_human_hang_out_street@female_arms_crossed@base", anim = "base", repet = 17}},
        {label = "Lägger i pengar  ", type = "anim", data = {lib = "anim@amb@clubhouse@jukebox@", anim = "insert_coins"}},
        {label = "Stå vid baren", type = "anim", data = {lib = "anim@amb@warehouse@toolbox@", anim = "idle"}},
        {label = "Peka på flygplan  ", type = "anim", data = {lib = "anim@mp_point", anim = "sweep_high_full_behind_left"}},
        {label = "Peka på fordon  ", type = "anim", data = {lib = "anim@mp_radio@garage@high", anim = "idle_a"}},
        {label = "Stäng av stora röda knappen  ", type = "anim", data = {lib = "anim@mp_radio@high_apment", anim = "action_a_bedroom"}},
        {label = "Krama snöboll  ", type = "anim", data = {lib = "anim@mp_snowball", anim = "pickup_snowball", repet = 0}},
        {label = "Håll upp händerna  ", type = "anim", data = {lib = "mp_country_bank_heist", anim = "guard_handsup_loop", repet = 0}},
        {label = "Klia dig i bakhuvudet  ", type = "anim", data = {lib = "mp_cp_stolen_tut", anim = "b_think", repet = 0}},
        {label = "Värma sig  ", type = "anim", data = {lib = "amb@world_human_stand_fire@male@base", anim = "base", repet = 1}}, 
        {label = "Duscha  ", type = "anim", data = {lib = "mp_safehouseshower@male@", anim = "male_shower_enter_into_idle", repet = 1}}, 
        {label = "Gör rundan  ", type = "scenario", data = {anim = "WORLD_HUMAN_BUM_FREEWAY"}},
        {label = "Hallå här är jag!  ", type = "anim", data = {lib = "misscarsteal2", anim = "come_here_idle_c"}},
        {label = "Hacka dator  ", type = "anim", data = {lib = "mp_prison_break", anim = "hack_loop", repet = 1}},
        {label = "Sova  ", type = "anim", data = {lib = "timetable@tracy@sleep@", anim = "idle_c", repet = 1}},
        }
    },

    {
        name  = 'attitudem',
        label = 'Gångstilar',
        items = {
        {label = "Normal man", type = "attitude", data = {lib = "move_m@generic", anim = "move_m@generic"}},
        {label = "Normal kvinna", type = "attitude", data = {lib = "move_f@generic", anim = "move_f@generic"}},
        {label = "Deprimerad man", type = "attitude", data = {lib = "move_m@depressed@a", anim = "move_m@depressed@a"}},
        {label = "Deprimerad kvinna", type = "attitude", data = {lib = "move_f@depressed@a", anim = "move_f@depressed@a"}},
        {label = "Business", type = "attitude", data = {lib = "move_m@business@a", anim = "move_m@business@a"}},
        {label = "Bestämd", type = "attitude", data = {lib = "move_m@brave@a", anim = "move_m@brave@a"}},
        {label = "Lugn", type = "attitude", data = {lib = "move_m@casual@a", anim = "move_m@casual@a"}},
        {label = "Tung person", type = "attitude", data = {lib = "move_m@fat@a", anim = "move_m@fat@a"}},
        {label = "Hipster", type = "attitude", data = {lib = "move_m@hipster@a", anim = "move_m@hipster@a"}},
        {label = "Skadad", type = "attitude", data = {lib = "move_m@injured", anim = "move_m@injured"}},
        {label = "Osäker snabb", type = "attitude", data = {lib = "move_m@hurry@a", anim = "move_m@hurry@a"}},
        {label = "Hobo", type = "attitude", data = {lib = "move_m@hobo@a", anim = "move_m@hobo@a"}},
        {label = "Ledsen", type = "attitude", data = {lib = "move_m@sad@a", anim = "move_m@sad@a"}},
        {label = "Biff", type = "attitude", data = {lib = "move_m@muscle@a", anim = "move_m@muscle@a"}},
        {label = "Chokad", type = "attitude", data = {lib = "move_m@shocked@a", anim = "move_m@shocked@a"}},
        {label = "Avvikande", type = "attitude", data = {lib = "move_m@shadyped@a", anim = "move_m@shadyped@a"}},
        {label = "Utmattad", type = "attitude", data = {lib = "move_m@buzzed", anim = "move_m@buzzed"}},
        {label = "Bestämd snabb", type = "attitude", data = {lib = "move_m@hurry_butch@a", anim = "move_m@hurry_butch@a"}},
        {label = "Hippie", type = "attitude", data = {lib = "move_m@money", anim = "move_m@money"}},
        {label = "Smygaktig springstil", type = "attitude", data = {lib = "move_m@quick", anim = "move_m@quick"}},
        {label = "Vandring", type = "attitude", data = {lib = "move_m@hiking", anim = "move_m@hiking"}},
        {label = "Polis", type = "attitude", data = {lib = "move_m@intimidation@unarmed", anim = "move_m@intimidation@unarmed"}},
        {label = "SWAG", type = "attitude", data = {lib = "move_m@swagger", anim = "move_m@swagger"}},
        {label = "Gay", type = "attitude", data = {lib = "move_f@maneater", anim = "move_f@maneater"}},
        {label = "Gay walk  ", type = "attitude", data = {lib = "move_f@gangster@ng", anim = "move_f@gangster@ng"}},
        {label = "Två väskor och högklackat  ", type = "attitude", data = {lib = "move_f@sassy", anim = "move_f@sassy"}},
        {label = "Arrogant  ", type = "attitude", data = {lib = "move_f@arrogant@a", anim = "move_f@arrogant@a"}},
        {label = "Getto  ", type = "attitude", data = {lib = "move_m@gangster@generic", anim = "move_m@gangster@generic"}},
	    {label = "Full  ", type = "attitude", data = {lib = "move_m@drunk@slightlydrunk", anim = "move_m@drunk@slightlydrunk"}},
	    {label = "Fullare  ", type = "attitude", data = {lib = "move_m@drunk@moderatedrunk", anim = "move_m@drunk@moderatedrunk"}},
	    {label = "Fullast  ", type = "attitude", data = {lib = "move_m@drunk@verydrunk", anim = "move_m@drunk@verydrunk"}},
	    {label = "Jag kan också springa  ", type = "attitude", data = {lib = "move_m@alien", anim = "move_m@alien"}},
        }
    },
    {
        name  = 'porn',
        label = 'Snusk',
        items = {
        {label = "Klias på bollarna", type = "anim", data = {lib = "mp_player_int_uppergrab_crotch", anim = "mp_player_int_grab_crotch", repet = 1}},
        {label = "Vink vink", type = "anim", data = {lib = "mini@strip_club@idles@stripper", anim = "stripper_idle_02", repet = 1}},
        {label = "Cigarette (Pose)", type = "scenario", data = {anim = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS"}},
        {label = "Bröstfokus", type = "anim", data = {lib = "mini@strip_club@backroom@", anim = "stripper_b_backroom_idle_b", repet = 1}},
        {label = "Strip Tease 1", type = "anim", data = {lib = "mini@strip_club@lap_dance@ld_girl_a_song_a_p1", anim = "ld_girl_a_song_a_p1_f", repet = 1}},
        {label = "Strip Tease 2", type = "anim", data = {lib = "mini@strip_club@private_dance@part2", anim = "priv_dance_p2", repet = 1}},
        {label = "Stip Tease 3", type = "anim", data = {lib = "mini@strip_club@private_dance@part3", anim = "priv_dance_p3", repet = 1}},
        {label = "Ta den i rumpan", type = "anim", data = {lib = "rcmpaparazzo_2", anim = "shag_loop_poppy", repet = 1}},
        {label = "Tryck den i rumpan", type = "anim", data = {lib = "rcmpaparazzo_2", anim = "shag_loop_a", repet = 1}},
        {label = "Kolla på strippor", type = "anim", data = {lib = "mini@strip_club@leaning@base", anim = "base", repet = 1}},
        {label = "Bli riden i bil  ", type = "anim", data = {lib = "oddjobs@assassinate@vice@sex", anim = "frontseat_carsex_loop_m", repet = 1}},
        {label = ": Baksäte  ", type = "anim", data = {lib = "random@drunk_driver_2", anim = "cardrunksex_loop_m", repet = 1}},
        {label = "Rid en person i bil  ", type = "anim", data = {lib = "oddjobs@assassinate@vice@sex", anim = "frontseat_carsex_loop_f", repet = 1}},
        {label = ": Baksäte  ", type = "anim", data = {lib = "random@drunk_driver_2", anim = "cardrunksex_loop_f", repet = 1}},
        {label = "Puta med rumpan  ", type = "anim", data = {lib = "random@street_race", anim = "_car_a_flirt_girl", repet = 1}}
        }
    },

    {
        name  = 'nya',
        label = 'Nya  ',
        items = {
        {label = "Roundkick  ", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "cap_a_player_a", repet = 0}},
        {label = "Bakåtvolt  ", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "flip_a_player_a", repet = 0}},
        {label = "Peta näsan  ", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@nose_pick", anim = "nose_pick", repet = 0}},
        {label = "Knuckles  ", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@knuckle_crunch", anim = "knuckle_crunch", repet = 0}},
        {label = "Fuck off  ", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@finger", anim = "finger", repet = 0}},
        {label = "Ligg och chilla  ", type = "anim", data = {lib = "switch@trevor@scares_tramp", anim = "trev_scares_tramp_idle_tramp", repet = 1}},
        {label = "Ligga och sola 1  ", type = "anim", data = {lib = "switch@trevor@annoys_sunbathers", anim = "trev_annoys_sunbathers_loop_girl", repet = 1}},
        {label = "Ligga och sola 2  ", type = "anim", data = {lib = "switch@trevor@annoys_sunbathers", anim = "trev_annoys_sunbathers_loop_guy", repet = 1}},
        {label = "Stå bredbent  ", type = "anim", data = {lib = "anim@heists@heist_corona@team_idles@male_a", anim = "idle", repet = 1}},
        {label = "Bakviktsgubbe  ", type = "anim", data = {lib = "amb@world_human_hang_out_street@male_b@idle_a", anim = "idle_b", repet = 1}},
        {label = "Stå och vänta :Feminint  ", type = "anim", data = {lib = "mp_move@prostitute@m@french", anim = "idle", repet = 1}},
        {label = "Stå och klia sig i skägget  ", type = "anim", data = {lib = "random@countrysiderobbery", anim = "idle_a", repet = 1}},
        {label = "Se tuff ut  ", type = "anim", data = {lib = "anim@heists@heist_corona@team_idles@female_a", anim = "idle", repet = 1}},
        {label = "Gunga till musik  ", type = "anim", data = {lib = "anim@heists@humane_labs@finale@strip_club", anim = "ped_b_celebrate_loop", repet = 1}},
        {label = "Diggar musiken  ", type = "anim", data = {lib = "anim@mp_celebration@idles@female", anim = "celebration_idle_f_a", repet = 1}},
        {label = "Stå och vänta 1  ", type = "anim", data = {lib = "anim@mp_corona_idles@female_b@idle_a", anim = "idle_a", repet = 1}},
        {label = "Stå och vänta 2  ", type = "anim", data = {lib = "anim@mp_corona_idles@male_c@idle_a", anim = "idle_a", repet = 1}},
        {label = "Stå och vänta 3  ", type = "anim", data = {lib = "anim@mp_corona_idles@male_d@idle_a", anim = "idle_a", repet = 1}},
        {label = "Stå och vänta 4  ", type = "anim", data = {lib = "amb@world_human_hang_out_street@female_hold_arm@idle_a", anim = "idle_a", repet = 1}},
        {label = "Stå och vänta :berusad  ", type = "anim", data = {lib = "random@drunk_driver_1", anim = "drunk_driver_stand_loop_dd1", repet = 1}},
        {label = "Diskutera 1  ", type = "anim", data = {lib = "misscarsteal4@actor", anim = "actor_berating_loop", repet = 1}},
        {label = "Diskutera 2  ", type = "anim", data = {lib = "oddjobs@assassinate@vice@hooker", anim = "argue_a", repet = 1}},
        {label = "Niga  ", type = "anim", data = {lib = "anim@mp_player_intcelebrationpaired@f_f_sarcastic", anim = "sarcastic_left", repet = 1}},
        {label = "Kom an då  ", type = "anim", data = {lib = "misscommon@response", anim = "bring_it_on", repet = 0}},
        {label = "Come at me bro  ", type = "anim", data = {lib = "mini@triathlon", anim = "want_some_of_this", repet = 0}},
        {label = "Armarna i kors  ", type = "anim", data = {lib = "anim@amb@nightclub@peds@", anim = "rcmme_amanda1_stand_loop_cop", repet = 1}},
        {label = "Kom hit  ", type = "anim", data = {lib = "gestures@f@standing@casual", anim = "gesture_hand_down", repet = 0}},
        {label = "Stå och sov  ", type = "anim", data = {lib = "mp_sleep", anim = "sleep_loop", repet = 1}},
        {label = "Värm upp för att slåss  ", type = "anim", data = {lib = "anim@deathmatch_intros@unarmed", anim = "intro_male_unarmed_c", repet = 0}},
        {label = "JAG  ", type = "anim", data = {lib = "gestures@f@standing@casual", anim = "gesture_me_hard", repet = 0}},
        {label = "Sätt dig på huk  ", type = "anim", data = {lib = "amb@medic@standing@tendtodead@base", anim = "base", repet = 1}},
        {label = "Meditera 1  ", type = "anim", data = {lib = "rcmcollect_paperleadinout@", anim = "meditiate_idle", repet = 1}},
        {label = "Meditera 2  ", type = "anim", data = {lib = "rcmepsilonism3", anim = "ep_3_rcm_marnie_meditating", repet = 1}},
        {label = "Meditera 3  ", type = "anim", data = {lib = "rcmepsilonism3", anim = "base_loop", repet = 1}},
        {label = "Hårdrock!  ", type = "anim", data = {lib = "anim@mp_player_intincarrockstd@ps@", anim = "idle_a", repet = 1}},
        {label = "Aldrig livet 1  ", type = "anim", data = {lib = "anim@heists@ornate_bank@chat_manager", anim = "fail", repet = 0}},
        {label = "Aldrig livet 2  ", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_no_way", repet = 0}},
        {label = "Ok Hand  ", type = "anim", data = {lib = "anim@mp_player_intselfiedock", anim = "idle_a", repet = 1}},
        {label = "Helt Slut  ", type = "anim", data = {lib = "re@construction", anim = "out_of_breath", repet = 1}},
        {label = "Starta Streetrace  ", type = "anim", data = {lib = "random@street_race", anim = "grid_girl_race_start", repet = 0}},
        
            }
    }

}